language: java
jdk:
 - oraclejdk8
addons:
 postgresql: "9.4"
sudo: required
services:
 - postgresql
before_install:
 - chmod +x mvnw
 - psql -c "CREATE DATABASE testing_db;" -U postgres
branches:
 only:
  - test
deploy:
 provider: heroku
 api_key:
  secure: "9808a904-fce1-413e-9eb3-be16f49d2c86"
  app: e1900020reactspring